AviaTrash/AviaTrash/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tickets/', include('aviaticket.urls')),  # Маршруты для приложения ticket
    path('personal/', include('users.urls')),  # Маршруты для приложения users
    path('', lambda request: redirect('tickets/', permanent=True)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AviaTrash/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import RegisterUserView, LoginUser, ProfileUser, CustomPasswordChangeView

app_name = 'personal'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='personal:login'), name='logout'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profile/password_change/', CustomPasswordChangeView.as_view(), name='password_change'),

]

AviaTrash/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name="Телефон")

    class Meta:
        db_table = 'auth_user'

AviaTrash/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from .models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email','phone', 'first_name', 'last_name', 'password1', 'password2',]
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', required=False,
                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 120, this_year - 18))))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'date_birth', 'first_name', 'last_name', 'phone']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'phone': 'Телефон'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class PasswordConfirmForm(AuthenticationForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-input'}),
        label="Пароль"
    )

AviaTrash/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import login, get_user_model
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, UpdateView
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from django.contrib.auth.views import PasswordChangeView, LoginView

from aviaticket.models import Ticket


class RegisterUserView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}

    def get_success_url(self):
        return reverse_lazy('list_tickets')



class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}
    success_url = reverse_lazy('list_tickets')

    def get_success_url(self):
        return reverse_lazy('personal:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tickets'] = Ticket.objects.filter(passenger=self.request.user).order_by('-booking_date')
        return context


# Смена пароля
class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy("personal:password_change_done")
    template_name = "users/password_change_form.html"
    form_class = UserPasswordChangeForm

AviaTrash/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="auth-container">
    <h2 class="auth-title">Вход</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Выводим поля формы -->

        {% if form.errors %}
            <div class="form-errors">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p class="error">{{ error }}</p> <!-- Показываем ошибки для каждого поля -->
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}

        <button type="submit" class="auth-button">
            Войти
        </button>
    </form>
    <p class="auth-link">
        Нет аккаунта? <a href="{% url 'personal:register' %}" class="auth-link-text">Регистрация</a>
    </p>
</div>
{% endblock %}

AviaTrash/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="password-changed-container">
    <h2 class="password-changed-title">Пароль изменен</h2>
    <p class="password-changed-message">Ваш пароль успешно изменен.</p>
    <p class="password-changed-link">
        <a href="{% url 'personal:profile' %}" class="password-changed-link-text">Вернуться в профиль</a>
    </p>
</div>
{% endblock %}

AviaTrash/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div class="password-change-form-container">
    <h2 class="password-change-form-title">Смена пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="password-change-form-button">
            Сменить пароль
        </button>
    </form>
</div>
{% endblock %}

AviaTrash/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="profile-container">
    <div class="profile-left">
        <!-- Форма редактирования профиля -->
        <h2 class="profile-title">Личный кабинет</h2>
        <form method="post" class="profile-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="profile-save-button">
                Сохранить изменения
            </button>
        </form>
        <p class="profile-password-change">
            <a href="{% url 'personal:password_change' %}" class="profile-link">Сменить пароль</a>
        </p>
    </div>

    <div class="profile-right">
        <!-- История покупок -->
        <h3>История покупок</h3>
        {% if tickets %}
            <ul class="ticket-list">
                {% for ticket in tickets %}
                    <li class="ticket-item">
                        <div class="ticket-details">
                            <p><strong>Рейс:</strong> {{ ticket.flight.flight_from }} → {{ ticket.flight.flight_to }}</p>
                            <p><strong>Дата:</strong> {{ ticket.flight.day_of_departure }}</p>
                            <p><strong>Цена:</strong> {{ ticket.flight.price }} ₽</p>
                            <p><strong>Статус:</strong> {{ ticket.status }}</p>
                        </div>

                        <!-- Кнопка для отмены билета -->
                        {% if ticket.status != 'cancelled' %}
                            <form method="post" action="{% url 'cancel_ticket' ticket.id %}" class="ticket-cancel-form">
                                {% csrf_token %}
                                <button type="submit" class="cancel-ticket-button">Отменить билет</button>
                            </form>
                        {% else %}
                            <p><strong>Билет отменен</strong></p>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>У вас еще нет купленных билетов.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

AviaTrash/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
    <p>
        Уже есть аккаунт? <a href="{% url 'personal:login' %}">Войти</a>
    </p>
</div>
{% endblock %}