AviaTrash/AviaTrash/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tickets/', include('aviaticket.urls')),  # Маршруты для приложения ticket
    path('personal/', include('users.urls')),  # Маршруты для приложения users
    path('', lambda request: redirect('tickets/', permanent=True)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AviaTrash/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import RegisterUserView, LoginUser, ProfileUser, CustomPasswordChangeView

app_name = 'personal'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='personal:login'), name='logout'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profile/password_change/', CustomPasswordChangeView.as_view(), name='password_change'),

]

AviaTrash/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Aviatrash{% endblock %}</title>
    <!-- Загружаем тег static -->
    {% load static %}
    <!-- Подключаем внешний файл стилей -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- Шапка -->
    <div class="header">
        <a href="{% url 'list_tickets' %}">Авиабилеты</a>
        <div class="auth-buttons">
            {% if user.is_authenticated %}
                <a href="{% url 'personal:profile' %}">Личный кабинет</a>
                <form action="{% url 'personal:logout' %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="logout-button">Выйти</button>
                </form>
            {% else %}
                <a href="{% url 'personal:login' %}">Войти</a>
            {% endif %}
        </div>
    </div>
    <!-- Основное содержимое -->
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Подвал -->
    <div class="footer">
        <p>&copy; 2024 Aviatrash - поиск самых дорогих авиабилетов. Все совпадения случайны. Все билеты выдуманы.</p>
    </div>
</body>
</html>